# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Should be an ECR repo
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

# use the same value as github slug
serviceName: ""

# info about the springboot container
container:
  port: 5000
  healthCheck: "/"
  profile: production
  cpu: 500m
  memory: 256Mi

# info about the EKS environment we are deploying to
eks:
  vaultAddr: "vault.vault.svc.cluster.local"
  vaultToken: ""
  certificateArn: ""

splunk:
  url: ""
  token: ""
  index: ""
  host: ""

autoscaler:
  averageUtilization: 50
  minReplicas: 1
  maxReplicas: 10
  scaleDownbehaviorvalue: 1
  scaleUpbehaviorvalue: 2
  scaleperiodSeconds: 60