apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"

  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      nodePort: 32122
      port: 80
      targetPort: !!int {{ .Values.container.port }}
  type: LoadBalancer