FROM amazoncorretto:17-alpine
EXPOSE 8080
USER 15000
# RUN mkdir -p /app/conf \
#     && mkdir -p /app/confd
# COPY --from=build /home/gradle/confd /app/confd/confd
# COPY confd /app/confd
COPY run.sh /app/run.sh
USER root
# RUN chmod a+x /app/confd/confd
RUN chmod a+x /app/run.sh
COPY app/build/libs/springboot-server-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["sh", "/app/run.sh"]