FROM --platform=linux/amd64 amazoncorretto:17-alpine
USER 15000
EXPOSE 8080
WORKDIR /app
# RUN mkdir -p /conf \
#     && mkdir -p /confd
# COPY --from=build /home/gradle/confd /app/confd/confd
COPY confd confd
COPY run.sh run.sh
# RUN chmod a+x /confd/confd
RUN chmod a+x run.sh
COPY app/build/libs/springboot-server-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["sh", "/app/run.sh"]
